- examples/example_helper.rb
- lib/dynflow/errors.rb
- lib/dynflow/executors/parallel.rb
- lib/dynflow/executors/parallel/core.rb
- lib/dynflow/executors/parallel/execution_plan_manager.rb
- lib/dynflow/executors/parallel/pool.rb
- lib/dynflow/executors/parallel/running_steps_manager.rb
- lib/dynflow/executors/parallel/work_queue.rb
- lib/dynflow/executors/parallel/worker.rb
- lib/dynflow/persistence.rb
- lib/dynflow/persistence_adapters/abstract.rb
- lib/dynflow/persistence_adapters/sequel.rb
- lib/dynflow/world.rb
- test/remote_via_socket_test.rb
- test/test_helper.rb
1. Retry several times when db error occurs
2. Terminate when the retries don't help
3. Let the executor to finish just after the workers are done:
don't wait for the whole task to finish.
> Better handling of databse connections errors

- lib/dynflow/world.rb
- test/test_helper.rb
There was a case where an event came right at the time of the core being
terminated, and ended up in the unresolved state.
Handling this in actor by dead letter routing is not as easy as it seems (as
making sure to read all the messages after termination turns out to not be so
straight forward). So for now we just make sure to refuse all the incoming
events as soon as possible.
> Fix tests on random unresolved future

- examples/sub_plans.rb
- lib/dynflow/action.rb
- lib/dynflow/action/with_sub_plans.rb
- lib/dynflow/execution_plan.rb
- lib/dynflow/execution_plan/steps/abstract.rb
- lib/dynflow/execution_plan/steps/plan_step.rb
- lib/dynflow/execution_plan/steps/run_step.rb
- lib/dynflow/persistence.rb
- lib/dynflow/persistence_adapters/sequel.rb
- lib/dynflow/persistence_adapters/sequel_migrations/003_parent_action.rb
- lib/dynflow/web_console.rb
- lib/dynflow/world.rb
- test/action_test.rb
- test/persistance_adapters_test.rb
- web/views/flow_step.erb
This patch adds support for triggering execution plans from a run phase
(a.k.a sub-plans) and waiting for the sub-plans to finish.
It's as simple as:
```ruby
class ActionWithSubPlan < Dynflow::Action
include Dynflow::Action::WithSubPlans
def create_sub_plans
10.times.map { trigger(SomeAction, input) }
end
end
```
The `Action::WithSubPlans` defines the `run` method and expects the action
to define `create_sub_plans` to return one or many triggered actions. The
`WithSubPlans` module takes care of waiting for the sub plans to finish,
and succeeding or failing after that.
The resuming behaviour can be also customized, by overriding the `resume`
method. By default, it re-creates the sub plans in case none of the sub
plans was planned successfully. Otherwise it checks, that all the sub plans …
> Sub plans support

- lib/dynflow/action.rb
The usage of suspend with block to get the suspended action reference is a bit
clumsy. This should help a bit with the readability.
> Allow using suspended_action reference before calling the suspend method

- lib/dynflow/action/polling.rb
- lib/dynflow/action/timeouts.rb
- lib/dynflow/testing/dummy_executor.rb
- lib/dynflow/testing/factories.rb
- lib/dynflow/testing/managed_clock.rb
- test/action_test.rb
This adds the ability for an action to call schedule_timeout(50), to
schedule when the polling should stop and the task be marked as failed.
In this simple implementation the above would cause the task to fail after 50
seconds.  Actions could override process_timeout to do more advanced things
> adding simple polling timeout mechanism

- doc/pages/source/documentation/index.md
- lib/dynflow/testing/assertions.rb
- test/testing_test.rb
The names of the some of the assert methods in assertions.rb are misspelled. This pull request fixes the spelling while also aliasing the old names so that you won't break anyone who is currently using them.
> fix spelling of assert methods

- lib/dynflow/web_console.rb
The 'sinatra' requires 'sinatra/main', which in 1.3.x version included some 
global methods and conflicted with others.
> require 'sinatra/base' instead of 'sinatra'

- lib/dynflow/action.rb
- test/action_test.rb
- web/views/flow_step.erb
The 'suspended' state might be misleading for some users not familiar much
with the dynflow terminology.
> Allow describing the action state in more user-oriented way

- lib/dynflow/coordinator.rb
- lib/dynflow/persistence_adapters/sequel_migrations/004_coordinator_records.rb
Some versions of MySQL seem to have issues with too big column indexes
> Limit the size of coordinator record id/class

- lib/dynflow/config.rb
The users should opt out, not opt in for this feature
> Put the default value for auto_rescue back to true

- examples/future_execution.rb
- lib/dynflow/action.rb
- lib/dynflow/execution_plan.rb
- lib/dynflow/execution_plan/steps/abstract.rb
- lib/dynflow/execution_plan/steps/plan_step.rb
- lib/dynflow/persistence.rb
- lib/dynflow/persistence_adapters/sequel.rb
- lib/dynflow/scheduled_plan.rb
- lib/dynflow/serializers/abstract.rb
- lib/dynflow/serializers/noop.rb
- lib/dynflow/web/console_helpers.rb
- lib/dynflow/world.rb
- test/future_execution_test.rb
- test/support/dummy_example.rb
- test/support/middleware_example.rb
- web/views/show.erb
They should be always 0.
Also, I hit an issue with a state, where the plan was in scheduled state, but
the scheduler record was not there: I updated the dynflow console to handle
this error better.
> Better progress reporting for pending/scheduled plans

- lib/dynflow/action/with_sub_plans.rb
- test/action_test.rb
This is handy when you want to know how many tasks are pending and you don't want to calculate `total - success - failed` all the time
> Keep pending subplans count in output

- dynflow.gemspec
- lib/dynflow.rb
- lib/dynflow/action.rb
- lib/dynflow/coordinator.rb
- lib/dynflow/execution_plan/output_reference.rb
- lib/dynflow/execution_plan/steps/error.rb
- lib/dynflow/persistence_adapters/sequel.rb
- lib/dynflow/scheduled_plan.rb
- lib/dynflow/serializable.rb
- lib/dynflow/serializer.rb
- lib/dynflow/testing/assertions.rb
- lib/dynflow/utils.rb
- lib/dynflow/web/console_helpers.rb
- lib/dynflow/web/filtering_helpers.rb
- lib/dynflow/world.rb
- test/persistence_test.rb
- test/testing_test.rb
Don't force the users to use active support extensions, unless they want it on
their own. Dynflow now can operate without active support in place. On the other hand,
for backward compatibility, as well as user convenience (if the HashWithIndifferent
access is there, they probably are already used to it), if the active support is present,
use it's features instead of the alternative implementation.
> Remove active_support dependency

- lib/dynflow/serializers/abstract.rb
- lib/dynflow/serializers/noop.rb
- test/support/dummy_example.rb
- test/test_helper.rb
With the current serializers interface it is almost impossible to extend what kind of object can existing serializer (de)serialize without reimplementing the whole serializer. With this patch one could do:
```ruby
class SerializerOne < Dynflow::Serializers::Noop
def serialize(arg)
arg.is_a?(Class) ? { :is_a => :class, :class_name => arg.to_s } : super(arg) # Serializers::Noop#serialize
end
def deserialize(arg)
arg[:is_a] == :class ? arg[:class_name].constantize : super(arg) # Serializers::Noop#deserialize
end
end
class SerializerTwo < SerializerOne
def serialize(arg)
arg.is_a?(Time) ? { :is_a => :time, :as_f => arg.to_f } : super(arg) # SerializerOne#serialize
end
def deserialize(arg)
arg[:is_a] == :time ? Time.at(arg[:as_f]) : super(arg) # SerializerOne#deserialize
end
end
```
to make …
> [suggestion] Changes interface of serializers

- lib/dynflow/config.rb
- lib/dynflow/coordinator.rb
- lib/dynflow/persistence_adapters/sequel.rb
- lib/dynflow/world.rb
- test/abnormal_states_recovery_test.rb
- test/test_helper.rb
Otherwise, invalidated worlds still keep the locks after being deleted.
How to reproduce:
1. start first world: it should get the delayed executor flag. 2. invalidate
the world 3. start another world
Expected: the new world is flagged as delayed executor Before fix: the world
is not delayed executor, because an old DelayedExecutorLock is still acquired
for the old world.
> Ensure the locks are released when world is being deleted

- lib/dynflow/execution_plan.rb
- lib/dynflow/executors/parallel/sequential_manager.rb
- lib/dynflow/middleware.rb
- lib/dynflow/middleware/common/transaction.rb
- lib/dynflow/middleware/register.rb
- lib/dynflow/middleware/resolver.rb
- lib/dynflow/world.rb
- test/middleware_test.rb
- test/support/middleware_example.rb
Together with ability to not use some middleware in some action, this
effective allows to turn off this functionality for some actions.
> Extract transaction logic into a middleware

- .travis.yml
- Gemfile
- dynflow.gemspec
concurrent-ruby team has always been nice to us in terms of backward
compatibility: let's rely on sem-ver for now and relax the version requirements
a bit
> Relax the concurrent ruby dependency

- lib/dynflow/dispatcher/client_dispatcher.rb
- lib/dynflow/persistence_adapters/sequel.rb
The dataset.each is not thread-safe, as described in documentation for the
method
https://github.com/jeremyevans/sequel/blob/4.20.0/lib/sequel/dataset/actions.rb#L126-L142
I suspect this to cause intermittent segmentation faults when under heaver
load.
> Fix thread-safety issue with sequel iteration

- lib/dynflow/persistence_adapters/sequel.rb
The Sequel's map method on dataset is not thread sefe, which might
occasionally lead to stack consistency issues. We already addreseed
similar case in 1510982b3d2b641ee4248cf6aa0ad9bd5392f828.
While it seemed it was the only place it might cause troubles,
similar thing could happen with auto-execute functionality,
when many tasks were pending. I've converted the rest of map
calls that return the result of map outside of the adapter to
make sure they are thread safe.
> Don't use sequel map method

- lib/dynflow/world.rb
In occasional cases, it might happen that invalidated world got
marked as stopped before, while we try set it as paused, which
is not a valid transition.
> Fix consistency check for stopped tasks

- lib/dynflow/world.rb
Currently when a Rails application initializes a new world, Dynflow may
use the logger from that world on the validation. However, that fails
because the logger hasn't been defined until the config for the wolrd
has been validated.
See how Config#validate calls 'config_for_world.world.logger'. That will
in turn call World#logger, which calls `logger_adapter` and fails
because the logger has not been set yet.
This commit ensure that there is a logger available every time we
initialize a world, therefore being able to validate the config on Rails
apps instead of failing
----------------------
I saw this failure just by using ForemanTasks with Dynflow. When I run any Rake task in Foreman, I get 'NoMethodError: undefined method `dynflow_logger' for nil:NilClass'  because the logger_adapter …
> Set logger before validating world

- lib/dynflow/persistence_adapters/sequel.rb
The `to_a` without `all` can still be thread unsafe at specific
circumstances.
> Fixes #16885 - use seuques' all instead of to_a

- lib/dynflow/world.rb
We hit an issue where we needed to invalidate a plan that was in planned
state. This lead to
"invalid state transition planned >> paused in <Dynflow::ExecutionPlan"
It turns out the only valid transition to paused state is from running,
so switching the condition to just do it then.
> When invalidating, pause only running steps

- lib/dynflow/world.rb
- test/abnormal_states_recovery_test.rb
Under some circumstances (such as manually deleting execution plans in
database), it might happen that the execution plan we try to invalidate
is no longer present. This patch allows to recover from this kind of
situations.
> Fixes #17177 - Handle invalidation with plans are missing

- lib/dynflow/execution_plan.rb
- lib/dynflow/throttle_limiter.rb
- test/executor_test.rb
- test/test_helper.rb
- web/views/plan_step.erb
Includes also a small refactoring which makes it easier to access
plan/run/finalize steps of execution plan
> Fixes #17212 - show plan timing info

- dynflow.gemspec
The latest version, 0.3.0 moved futures to promises and the API
was renamed. See the changes on:
https://github.com/ruby-concurrency/concurrent-ruby/pull/522/
> Pin concurrent-ruby-edge to 0.2.3

- dynflow.gemspec
- lib/dynflow/world.rb
Minimal reproducer for this issue:
1. Have Foreman/Satellite with at least one Dynflow task running.    (Actions::Candlepin::ListenOnCandlepinEvents in Katello/Satellite is a good candidate)
2. kill dynflow executor while the task is running: pkill -9 -f dynflow_executor
3. foreman-rake db:migrate
You should see errors in the output
```
E, [2017-01-24T03:00:53.032499 #9544] ERROR -- /client-dispatcher: No executor available (Dynflow::Error)
```
With this patch the migration should proceed with no errors.
> Fixes #18206 - Redispatch invalid requests only when executor exists

- Gemfile
New bundler has issues resolving more complicated dependencies,
pinning the ext we use for testing to 1.0.3 for now.
> Pin concurrent-ruby-ext to 1.0.3

- dynflow.gemspec
- lib/dynflow.rb
- lib/dynflow/active_job/queue_adapter.rb
- test/activejob_adapter.rb
This commit adds an adapter to allow Dynflow to be used as an ActiveJob
backend. After this, jobs in Rails can be defined as ActiveJob::Base,
enqueued with "SampleJob.perform_later" or scheduled with
"SampleJob.set(:wait => 10.seconds).perform_later('abc')"
https://gist.github.com/anonymous/429e7171e867c94182839a4b0d1ddddc
> ActiveJob adapter

- lib/dynflow.rb
Calling .include on a class does not work as it's a private method in
Ruby pre 2.1.
https://github.com/ruby/ruby/blob/v2_1_0/NEWS#L96 contains the info
```ruby
irb(main):001:0> RUBY_VERSION
=> "2.0.0"
irb(main):002:0> Module.public_instance_methods.grep(/^include$/)
=> []
irb(main):003:0> Module.private_instance_methods.grep(/^include$/)
=> [:include]
irb(main):001:0> RUBY_VERSION
=> "2.1.5"
irb(main):002:0> Module.public_instance_methods.grep(/^include$/)
=> [:include]
irb(main):003:0> Module.private_instance_methods.grep(/^include$/)
=> []
irb(main):001:0> RUBY_VERSION
=> "2.2.3"
irb(main):002:0> Module.public_instance_methods.grep(/^include$/)
=> [:include]
irb(main):003:0> Module.private_instance_methods.grep(/^include$/)
=> []
```
Sorry for the breakage @iNecas - if you can release …
> Ruby 2.0.0 compatibility for ActiveJob

- lib/dynflow/action.rb
- lib/dynflow/action/with_bulk_sub_plans.rb
- lib/dynflow/action/with_sub_plans.rb
- lib/dynflow/throttle_limiter.rb
- test/batch_sub_tasks_test.rb
- test/concurrency_control_test.rb
- include the `::Dynflow::Action::WithBulkSubPlans` module into the action.
- implement `total_count` method returning the total count of plans we want to create
- implement `entries(FROM, SIZE)` method returning the batch starting at position `FROM` and spanning `SIZE` items
- the `BATCH_SIZE` constant can be redefined to change the size of the batch
- use `current_batch` inside `create_sub_plans` to get the current batch
> Batch planning of sub tasks

- Gemfile
- examples/memory_limit_watcher.rb
- lib/dynflow/testing/in_thread_world.rb
- lib/dynflow/watchers/memory_consumption_watcher.rb
- lib/dynflow/world.rb
- test/memory_cosumption_watcher_test.rb
- test/testing_test.rb
- test/world_test.rb
This watcher polls the memory size of the process it runs in and terminates the world if memory limit is exceeded.
This commit also adds `terminated` event to `World` class, so anyone can add a listener that will perform tasks after a world is terminated.
> Fixes #17175 - Added watcher that can terminate a world

- lib/dynflow/action.rb
- lib/dynflow/active_job/queue_adapter.rb
- lib/dynflow/execution_plan.rb
- lib/dynflow/persistence_adapters/sequel.rb
- lib/dynflow/persistence_adapters/sequel_migrations/010_add_execution_plans_label.rb
- test/execution_plan_test.rb
- test/persistence_test.rb
- test/support/code_workflow_example.rb
- web/views/index.erb
- web/views/show.erb
The value of the label is determined by the `action#label`. The default
goes to the `class.name` but can be overriden, for example ActiveJob can
override it with the job class name.
> Add label to execution_plan

- lib/dynflow/errors.rb
- lib/dynflow/execution_plan.rb
- lib/dynflow/world.rb
- test/execution_plan_test.rb
- web/views/show.erb
In a corner case, the data can be inconsistent in a way, that prevents
the world to be invalidate properly. Although this is usually a result
of unsafe manipulation with data on database level, we need to try
to resolve the situation to at least keep clean the runtime data properly,
as there is not much more we can do about it.
> Fixes #19146 - handle invalid plans when invalidating worlds

- dynflow.gemspec
- lib/dynflow/persistence_adapters/sequel.rb
To get rid of
```ruby
SEQUEL DEPRECATION WARNING: requiring 'sequel/no_core_ext' is deprecated and will be removed in Sequel 5.  Just require 'sequel' instead.
<--- snip --->
SEQUEL DEPRECATION WARNING: Calling a dataset filtering method with multiple arguments or an array where the first argument/element is a string is deprecated and will be removed in Sequel 
5.  Use Sequel.lit("start_at <= ? OR (start_before IS NOT NULL AND start_before <= ?)", 2017-05-17 07:43:27 UTC, 2017-05-17 07:43:27 UTC) to create an SQL fragment expression and pass that
to the dataset filtering method, or use the auto_literal_strings extension.
```
Maybe pinning activerecord and/or sequel versions might be reasonable
> Remove things which will be deprecated in sequel >= 5

- dynflow.gemspec
in e9c89e7 we pinned concurrent-ruby-edge to ~> 0.2.3, because that was the latest available version at that time. but in reality we really want *any* version of the 0.2.x series, just not 0.3.x. let's soften the 
dependency accordingly. this allows the use of dynflow with older c-r-e releases.
I did run the unit-tests on both, c-r-e 0.2.0 and 0.2.4, and they run fine.
> pin concurrent-ruby-edge to any version of the 0.2.x series

- Gemfile
Due to requirements on dependencies
> Pin sinatra to 1.4.8 for ruby < 2.2.2

- lib/dynflow/executors/parallel/core.rb
- lib/dynflow/executors/parallel/pool.rb
The way we passed the arguments to the handle_persistence_error was
wrong before.
> Fixes #20380 - fix argument error on :handle_peristence_error

- lib/dynflow/config.rb
- lib/dynflow/persistence.rb
- lib/dynflow/persistence_adapters/abstract.rb
- lib/dynflow/persistence_adapters/sequel.rb
- lib/dynflow/world.rb
- test/persistence_test.rb
- test/test_helper.rb
When execution plan is deleted it is exported along with actions and
steps. The backup is controlled by two configuration options -
backup_deleted_plans and backup_dir. The data are exported in CSV format
one file per plans, actions and steps. The files are created under the
backup_dir and daily subdirs for easier rotations.
> Refs #20352 - Backup execution plans on their deletion

- examples/sub_plans.rb
- lib/dynflow/action.rb
- lib/dynflow/action/with_bulk_sub_plans.rb
- lib/dynflow/action/with_polling_sub_plans.rb
- lib/dynflow/action/with_sub_plans.rb
- test/action_test.rb
> Polling sub tasks

- lib/dynflow.rb
- lib/dynflow/actors.rb
- lib/dynflow/actors/execution_plan_cleaner.rb
- lib/dynflow/config.rb
- lib/dynflow/coordinator.rb
- lib/dynflow/delayed_executors/abstract.rb
- lib/dynflow/persistence.rb
- lib/dynflow/persistence_adapters/sequel.rb
- lib/dynflow/world.rb
- test/execution_plan_cleaner_test.rb
It is disabled by default, needs to be enabled in a world's config. For the usage on smart-proxy this should be good to go since there's mostly one or two kinds of tasks (rex and ansible), so we probably don't need fine grained controls for setting different interval for different actions.
> Execution plan cleaner

- lib/dynflow/action/rescue.rb
- lib/dynflow/director.rb
- lib/dynflow/execution_plan.rb
- test/rescue_test.rb
- test/support/rescue_example.rb
This PR includes two fixes for rescue strategy
Fixes #20647 - fix calculation of rescue strategy for complex actions
Since ba6300f, we were considering also pending and successful steps when
calculating the rescue strategy. This made the auto_rescue not working
properly, as any action with `Pause` rescue strategy (which is considered
by default) would lead to pause of the task.
This change makes the rescue strategy working properly again, while keeping
the Fail strategy working as well.
Fixes #20648 - support for multiple auto-rescues in the plan
Currently, when an error occurs and skip rescue strategy applies, it
auto-rescues only at the first failure: the auto-rescue is not applied for
further failures.
After this change, we don't check only if the plan was already rescued or
not, but …
> Rescue strategy fixes and enhancements

- lib/dynflow/rails/configuration.rb
In Rails 5 Rake is defined but `Rake.application` is only present when running via rake.
> Fix Rails 5 compatibility

- examples/singletons.rb
- lib/dynflow/action.rb
- lib/dynflow/action/singleton.rb
- lib/dynflow/coordinator.rb
- lib/dynflow/execution_plan.rb
- lib/dynflow/middleware.rb
- lib/dynflow/middleware/common/singleton.rb
- lib/dynflow/world.rb
- test/action_test.rb
- test/execution_plan_test.rb
An action into which this module is included (singleton action from
now on) on which there should be only one instance running at any
given time.
This means the action tries to obtain a lock at the beginning of its
plan phase and fails if it doesn't acquire it. At each Action#run it
checks if it is still holding the lock.  If it does, it goes on,
otherwise tries to reacquire it. It behaves the same way during the
lock reacquiring as in plan phase.
Finally, it releases the lock at the end of finalize phase. If
things go wrong, locks should get released when the execution plan
holding them gets invalidated.
Please make sure singleton actions release the lock they're holding
in case they encounter any error from which they can't recover.
> Introduce Singleton action module

- lib/dynflow/rails/configuration.rb
Makara can be used as a wrapper around the standar ActiveRecord adapter.
This patch should allow users using Dynflow while using this adapter.
See [1] for such an example.
[1] - https://groups.google.com/d/msg/foreman-users/ORak_xvLi-U/Qy56C3SSAAAJ
> Add support for makara adapter

- lib/dynflow/delayed_executors/abstract_core.rb
in many cases, I'm seeing trace in the logs where they are not required, for example:
* ERROR -- /executor-dispatcher: ActiveRecord::ConnectionNotEstablished (ActiveRecord::ConnectionNotEstablished)
* invalid worlds found {..}
* /home/foreman/gems/gems/dynflow-0.8.34/lib/dynflow/stateful.rb:35:in `set_state'
while the first two are clear for me, I think the last one is missing printing out the actual exception, but probably can be fixed in another pr.
I'm suggesting to change to WARN so users can change their log level and see the trace, but by default it doesn't log in production the full trace.
> change logging level for failed actions

- dynflow.gemspec
There is an issue with minitest 5.11.x + Rails 5.1. It should be fixed
in Rails (https://github.com/rails/rails/pull/30800), however, it's not
released yet.
5.11.x gives us issues described in
https://github.com/seattlerb/minitest/issues/730.
> Pin minitest to -> 5.10.0

- dynflow.gemspec
- test/test_helper.rb
In 35efa3bdc9d1324709bc2200b0f6a42a85cc1f54, we've pinned the minitest
version because the new version was not compatible with the Rails
minitest plugin.
I've noticed also, that the Rails plugin does other non-standard things,
such as printing the test errors inline, as opposed to at the end of the
test run. This was not working nicely, as currently, our tests are quite
verbose at the output.
Putting the fact that we should be less verbose at the test run, I don't
like the behavior the Rails introduces and there is no nice way how to
disable this behavior, when defining the test Rake task.
Together with the fact, that Rails is currently broken with minitest
5.11.x, disabling autoloading of the minitest plugins seems like the
best thing we can do.
The disabling was introduced in …
> Disable minitest plugins

- lib/dynflow/action/with_bulk_sub_plans.rb
- lib/dynflow/execution_plan/steps/abstract.rb
- test/action_test.rb
- test/test_helper.rb
In case of empty set of sub plans, the aciont with WithBulkSubPlans was
calculating progress as 0./0, which lead to NaN. While some
databases (such as Postgres), were converting this value to 0, on
SQLite, we were getting:
Sequel::DatabaseError: SQLite3::SQLException: no such column: NaN
The code fixes the WithBulkSubPlans progress calculation + ensuring that
we handle unexpected progress value better.
> Fix NaN as progress value for WithBulkSubPlans

- .travis.yml
Run different databases only on the newest ruby version. Use postgres by
default.
> Reduce the test matrix

- lib/dynflow/persistence_adapters/sequel_migrations/011_add_uuid_column.rb
Dynflow DB with 20002 execution plans, consisting of 100002 actions and 200004 steps.
| | execution_plans | actions | steps
|-| -----------------:|---------:|--------:|
as string | 27 MB | 91 MB | 197 MB
as uuid | 24 MB | 59 MB | 127 MB
change | -3 MB | -32 MB | -70 MB
Gist showing change in schema: https://gist.github.com/adamruzicka/7630827c1be46a741cc2b453bfdb8c20/revisions#diff-39859e34161f0cb6f5f50974282a2593
> Use UUID column type on PostgreSQL

- lib/dynflow/delayed_executors/abstract_core.rb
- lib/dynflow/execution_plan/hooks.rb
- lib/dynflow/executors.rb
- lib/dynflow/executors/parallel/worker.rb
- lib/dynflow/transaction_adapters/abstract.rb
- lib/dynflow/transaction_adapters/active_record.rb
In case we run user code inside Dynflow threads, we should make sure to
clean common mess, such as leaking ActiveRecord connections.
> Fixes #22839 - defensive cleanup when running user-defined code

- lib/dynflow/rails.rb
- lib/dynflow/rails/configuration.rb
- lib/dynflow/world.rb
- test/daemon_test.rb
Otherwise, the actions performed during the validity check could lead to
issues like this:
RuntimeError: The Dynflow world was not initialized yet. If your plugin
uses it, make sure to call Rails.application.dynflow.require! in some
initializer
> Fixes #22837 - postpone validation checks in Rails environment

- lib/dynflow/delayed_executors/abstract_core.rb
- test/future_execution_test.rb
When a process is terminated while the delayed executor is processing,
it can lead to the situation, where the plan is in weird state (such as
:planning, or :stopped), while the delayed record is still present.
This patch fixes this by returning the `:planning` state back to
`:scheduled`, and in case of other states, just skipping that, because
in that case, other resiliency mechanisms would already handled that, so
we need just to make sure we delete the delayed record at the end.
> Fixes #23156 - handle unexpected plan states

- lib/dynflow/execution_plan.rb
- test/execution_plan_hooks_test.rb
The cancelled state on steps introduced in a023b2907 caused the
regression, where `on_failure` hooks were not run on `cancelling`.
I've also noticed we don't run them on `warning` as well. After the
change, we do run it in both cases.
> Refs #21358 - run on_failure hook on cancelled and warning states

- lib/dynflow/rails/daemon.rb
- test/daemon_test.rb
In development environment, the dynflow lazy loading could lead to not
initializing the executor.
> Fixes #23501 - ensure to initialize dynflow in executor

- lib/dynflow/execution_plan.rb
- lib/dynflow/middleware.rb
- lib/dynflow/middleware/stack.rb
- lib/dynflow/middleware/world.rb
Rationale:
When we moved repetition triggering for recurring actions into a hook, suddenly it wasn't being executed as the original user and in the original taxonomies. This will allow us to fix it once by allowing the middlewares to restore user and taxonomies before running the hook instead of having to deal with the same issue for every recurring action separately.
> Allow middlewares to be executed around hooks

- lib/dynflow/config.rb
- lib/dynflow/connectors/abstract.rb
- lib/dynflow/dispatcher/client_dispatcher.rb
- lib/dynflow/executors/parallel.rb
- lib/dynflow/executors/parallel/core.rb
- lib/dynflow/rails/configuration.rb
- lib/dynflow/web/console.rb
- lib/dynflow/world.rb
- test/abnormal_states_recovery_test.rb
- test/dispatcher_test.rb
- test/test_helper.rb
- test/world_test.rb
- web/views/worlds.erb
Some other projects use Pings quite extensively (run them at the start
of every actions) so it seemed like a good idea to cache them to reduce
the number of sent messages.
This commit introduces such mechanism. Cache records are added either
when a response to a Ping or a Ping is received. This way, both
participants in the communication have the other one in their own
caches.
Furthermore a world tries to announce its availability (pings all other
worlds) at the end of its #initialize.
> Cache Ping messages

- lib/dynflow/config.rb
- lib/dynflow/delayed_executors/abstract.rb
- lib/dynflow/dispatcher.rb
- lib/dynflow/dispatcher/client_dispatcher.rb
- lib/dynflow/executors/parallel/core.rb
- lib/dynflow/rails.rb
- lib/dynflow/world.rb
- lib/dynflow/world/invalidation.rb
- test/daemon_test.rb
- test/dispatcher_test.rb
We do two things to achieve this:
1. re-initialize the delayed executor if some worlds were invalidated
2. don't use ping cache at executors startup - this way we handle the
case, when the executor gets force killed and the timeout doesn't
expire before the new executor goes up. I've increased the ping
timeout to avoid false negatives
Steps to reproduce:
1. run executor with rails environment (with foreman-tasks)
2. force kill the executor
3. run executor again
Without this patch: the old executor doesn't get invalidated at startup and even it it gets (when waiting for a minute between step 2 and 3, it doesn't get the delayed executor started.
> Fixes #24119 - ensure delayed executor is preserved after invalidation

- .rubocop.yml
- lib/dynflow/coordinator_adapters/sequel.rb
- lib/dynflow/director.rb
- lib/dynflow/errors.rb
- lib/dynflow/executors/parallel/core.rb
- lib/dynflow/executors/parallel/pool.rb
- lib/dynflow/executors/parallel/worker.rb
- lib/dynflow/persistence_adapters/sequel.rb
- test/executor_test.rb
- test/test_helper.rb
Before this patch, we were considering every persistence issue as
something that we could retry on and the only resolution if that was not
successful, was executor termination.
With this patch, we keep the retry mechanism just for connection issues
and for other persistence issues, we just clean up the runtime.
> Handle situation when execution plan gets deleted

- lib/dynflow/active_job/queue_adapter.rb
There is no point in pausing active job, as they never consist from more
than one step.
> Fixes #24761 - skip rescue strategy for active job

- lib/dynflow/rails/configuration.rb
Before this commit, the setting would be simply overridden by 5.
> Fixes #24829 - Fixes setting pool size when using rails

- lib/dynflow/connectors/abstract.rb
- lib/dynflow/connectors/database.rb
- lib/dynflow/connectors/direct.rb
- lib/dynflow/world.rb
This patch adds a timeout for some connector events, waiting for
termination hooks, as well as a global termination timeout to make sure we
don't get stuck forever.
I've added the extraction of the method to separate commit, so that it's easier
to see the changes in the orinial method.
> Fixes #25021 - add more termination timeouts

- lib/dynflow/logger_adapters/simple.rb
Otherwise, the wrappers are not transparent enough, and the users can get issues
with some methods missing.
> Add method missing to logger wrapper

- lib/dynflow/rails/daemon.rb
`#dynflow_logger` is not defined on `world`
> Use correct logger in Rails daemon

- lib/dynflow/executors/parallel/worker.rb
Previously, we would not respond to the pool in case of any exception
coming from the `work_item.execute`. Even though I don't think we expect
any other exceptions other than PeristenceError, it didn't feel right not to
respond on any exception that might occur.
When I looked at API of concurrent ruby, it seems like we can use check on
`global_io_executor` to check it's still operational.
> Enhance fix for termination with running action

- lib/dynflow/action.rb
- lib/dynflow/execution_plan/steps/plan_step.rb
- test/execution_plan_test.rb
Previously the following would hold as a definition of a sub plan:
Execution plan E2 is a sub plan of E1 if E2 has at least one action with
caller_execution_plan_id set to E1.id.
Let's consider an execution plan E1 with a single action A1. A1's
caller_{execution_plan,action}_id is nil and everything is in order.
However if we would plan action A2 from A1, A2's caller_execution_plan_id would
be set to E1.id and caller_action_id to A1.id. According to the previous
definition E1 would be considered a sub plan of itself.
With this patch only execution plan's entry action can have
caller_execution_plan_id set. This way, we shouldn't reach a situation where an
execution plan is its own sub plan.
> Make sure an execution plan cannot be its own sub plan

- .travis.yml
This fixes the following issue:
```
The program 'bundle' is currently not installed. To run
'bundle' please ask your administrator to install the package 'bundler'.
```
Seems like the issue is the bundler 2.0 is not compatible with
ruby < 2.3.0
> Fix travis on ruby 2.2

- lib/dynflow/executors/parallel/pool.rb
- lib/dynflow/web/console.rb
- test/executor_test.rb
- test/world_test.rb
This was leading to some unexpected behavior: using simple FIFO instead.
This PR aslo adds simple benchmarking script to compare the behavior: ideal in
combination with the telemetry.
> Fixes #24435 - Remove round robin from the job storage

- .rubocop.yml
- lib/dynflow/action/with_sub_plans.rb
- lib/dynflow/active_job/queue_adapter.rb
- lib/dynflow/execution_plan.rb
- lib/dynflow/world.rb
- test/activejob_adapter_test.rb
- test/execution_plan_test.rb
Also make execution_plan.id match active_job.id, which makes it easier to
use single uuid to search the data across the active job and dynflow realm.
As part of this change, we've made it possible to set the execution plan id
to custom value (the developer needs to be careful to not use duplicate keys: with great power
comes great responsiblity).
> Make the job_provider_id available in the worker

- test/abnormal_states_recovery_test.rb
Using the same plan uuid in two tests doesn't seem like a good idea.
Setting the uuid in abnormal_states_recovery_test to be different
than the one in execution_plan_test.rb
Combination of https://github.com/Dynflow/dynflow/pull/319 and https://github.com/Dynflow/dynflow/pull/317
lead to issues like:
```
consistency check::#coordinator_validity_check::with singleton action locks#test_0001_unlocks orphaned singleton action locks
[/home/travis/build/Dynflow/dynflow/test/abnormal_states_recovery_test.rb:335]:
Expected [#<Dynflow::Coordinator::SingletonActionLock:0x000000056f2200 @data={"class"=>"Dynflow::Coordinator::SingletonActionLock", "owner_id"=>"execution-plan:98ddd0fa-5ba9-44a6-b72d-2ad8b05dc802", "execution_plan_id"=>"98ddd0fa-5ba9-44a6-b72d-2ad8b05dc802", …
```
> Fix intermittent failures around invalid uuid

- lib/dynflow/director.rb
- lib/dynflow/director/execution_plan_manager.rb
- lib/dynflow/execution_plan.rb
- lib/dynflow/world/invalidation.rb
- test/abnormal_states_recovery_test.rb
- test/executor_test.rb
- test/rescue_test.rb
- test/test_helper.rb
The previous rescue algorithm put the task into paused state and then we
looked at what are the possible rescue strategies, and if it was to
skip, we marked the steps to skip and executed the task again.
Several problems where there with this approach:
- the execution plan needed to get back at the beginning of the workers
queue, so there was additional overhead with this
- the execution history got confusing, because there was note about
finishing and starting the execution again
- it's hard to hook events (such as logging or notifications) for paused
tasks, as when the plan was getting into paused state, we didn't know
it would be rescued immediately.
This is a prerequisite for allowing notifications on paused tasks.
> Reduce status updates on rescue

- lib/dynflow/logger_adapters/formatters/abstract.rb
- lib/dynflow/logger_adapters/simple.rb
Before this patch, we couldn't do things like this:
logger.debug { "Message that needs some calculation" }
> Support for logger message with block

- lib/dynflow/delayed_plan.rb
- lib/dynflow/director.rb
- lib/dynflow/director/execution_plan_manager.rb
- lib/dynflow/execution_plan.rb
- lib/dynflow/world/invalidation.rb
- test/execution_plan_hooks_test.rb
After 8bae5b62b273, we had a code that was updating `state` outside of
`update_state` method, which meant the hooks (observed with `:paused`
state) were not run when `auto_rescue` was enabled.
I've also noticed coupling between adding history and `update_state`
methods, so I put it directly into `update_state`.
> Fix pause hooks + refactor history notices

- lib/dynflow/action.rb
- test/action_test.rb
- test/execution_plan_hooks_test.rb
Before this patch, the root_action was returning correctly only in
planning phase.
Checking for @caller_action_id.nil? or @caller_execution_plan_id being
set (which means the the caller_action_id is coming from different
execution plan id) should extend this functionality for other phases as
well.
> Fix root_action for post-planning phase

- lib/dynflow/rails/daemon.rb
- test/daemon_test.rb
Also set this option to default 60 seconds so that long running
task is more likely to finish before being killed.
> Fixes #27123 - Make "force_kill_waittime" option adjustable

- .travis.yml
- Gemfile
- dynflow.gemspec
- lib/dynflow/actor.rb
- lib/dynflow/logger_adapters/formatters/exception.rb
This helps a lot figuring out where the particular errors are coming
from.
Before - long backtrace that doesn't lead to the original caller:
```
E, [2019-05-25T22:12:00.588309 #13630] ERROR -- /client-dispatcher: No executor available (Dynflow::Error)
/home/inecas/active/projects/foreman-main/dynflow/lib/dynflow/connectors/direct.rb:44:in `find_receiver'
/home/inecas/active/projects/foreman-main/dynflow/lib/dynflow/connectors/direct.rb:29:in `handle_envelope'
/home/inecas/active/projects/foreman-main/dynflow/lib/dynflow/actor.rb:6:in `on_message'
/home/inecas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/concurrent-ruby-edge-0.4.1/lib-edge/concurrent/actor/context.rb:46:in `on_envelope'
/home/inecas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/concurrent-ruby-edge-0.4.1/lib-edge/concurr …
```
> Log the original trace for the actor

- lib/dynflow/coordinator.rb
- lib/dynflow/world.rb
- lib/dynflow/world/invalidation.rb
- test/abnormal_states_recovery_test.rb
- test/executor_test.rb
If the process planning an execution plan is killed before it can finish,
there's a chance it will get stuck in this state forever. This commit introduces
planning locks so we can stop the execution plans which are not really being
planned anymore during invalidation.
> Ensure we don't end up with plans stuck in planning

- lib/dynflow/executors/sidekiq/core.rb
- lib/dynflow/executors/sidekiq/redis_locking.rb
- test/executor_test.rb
Upon startup, the orchestrator checks if dynflow_orchestrator_uuid key is unset in Redis. If so, it acquires an orchestrator lock by associating the uuid of the orchestrator's world with the key. However this lock has limited time to live and needs to be periodically
refreshed.
If the key is set, the orchestrator goes into passive mode and periodically polls the lock's status. If it manages to acquire the lock, it becomes the active orchestrator.
Active orchestrator periodically updates the record in Redis to ensure its freshness.
Redmine: https://projects.theforeman.org/issues/27412
>  Allow running multiple orchestrators in active-passive mode

- examples/remote_executor.rb
- lib/dynflow/executors/sidekiq/orchestrator_jobs.rb
If the worker is shut down, execution of its work item is interrupted, but it
still sends the work done job to the orchestrator and requeues the job to be
executed again. This leads to two issues - step is not saved after the worker is
interrupted and the job is executed twice.
This patch disables the job requeueing and makes orchestrator save the step, if
the step's error is ::Sidekiq::Shutdown. This solves both of the issues.
If the worker is not interrupted, but is SIGKILLed, then the regular worker
crash handling kicks in, reruns the job and the it fails because the step is in
an unexpected state.
For example usage see https://github.com/Dynflow/dynflow/compare/master...adamruzicka:abnormal-termination-example?expand=1
> Handle cases where worker is shut down

- lib/dynflow/rails/configuration.rb
We used to check if `Sidekiq.options[:dynflow_executor]` is not nil, but in
rails this was being set after the world was initialized. That led to Parallel
core being used instead of Sidekiq one.
> Properly detect which executor core to use

- lib/dynflow/persistence_adapters/sequel_migrations/001_initial.rb
The full error was:
```
Sequel::DatabaseError: PG::UndefinedObject: ERROR: constraint
"dynflow_steps_execution_plan_uuid_fkey1" of relation "dynflow_steps" does not
exist
```
It turned out PostgreSQL names foreign key constraints differently than previous
versions. This could cause issues when we try to migrate string columns to
UUIDs, because we have to temporarily remove specific foreign key constraints
which didn't exist due to the new naming scheme. To solve this, this patch
"hard-codes" the names of foreign key constraints which we need to touch.
> Fix Sequel::DatabaseError during migrations

- lib/dynflow/executors/sidekiq/orchestrator_jobs.rb
When the worker is stopped, ::Sidekiq::Shutdown exception is raised
inside the worker. In case that happens, we need to save the step on
from the orchestrator's side to not lose data and progress. That means
we have to check every single step if it has an error and if so, what
kind of error it was. Originally we checked whether the exception is
an instance of ::Sidekiq::Shutdown. This commit changes this behavior
to not check the instance, but the class itself.
This may not work if the class is a subclass of the class we're
checking for, but given we expect one specific exception class, I'd
say this is safe to do.
> Do not instantiate an exception to check its class

- lib/dynflow/world.rb
Concurrent-ruby-1.1.3 changed a lot of method names around futures and
events. Apparently we missed one of those when adjusting the code to be
compatible with this version.
> Use correct method name for resolving events

- lib/dynflow/execution_plan.rb
- lib/dynflow/flows.rb
- lib/dynflow/flows/abstract.rb
- lib/dynflow/flows/abstract_composed.rb
- lib/dynflow/flows/atom.rb
- lib/dynflow/flows/concurrence.rb
- lib/dynflow/flows/registry.rb
- lib/dynflow/flows/sequence.rb
- lib/dynflow/persistence_adapters/sequel.rb
- test/flows_test.rb
This new format is roughly 10 times more efficient than what we had previously.
```json
{
"class": "Dynflow::Flows::Concurrence",
"flows": [
{
"class": "Dynflow::Flows::Atom",
"step_id": 3
},
{
"class": "Dynflow::Flows::Sequence",
"flows": [
{
"class": "Dynflow::Flows::Atom",
"step_id": 4
},
{
"class": "Dynflow::Flows::Atom",
"step_id": 7
}
]
},
{
"class": "Dynflow::Flows::Atom",
"step_id": 10
}
]
}
```
```json
["C",  3,
["S", 4, 7],
10]
```
Note: both examples were reformatted for readability, in the db they are just `MultiJson.dump`ed
> Store flow data in a more compact manner

- lib/dynflow/world/invalidation.rb
This should prevent errors like invalid transition stopped >> stopped during
world invalidation.
> Do not try to change plan's state if it is in it already

- lib/dynflow/rails.rb
- lib/dynflow/rails/configuration.rb
Historically dynflow distinguished between executors (those who perform work)
and clients (those who produce work). Executors increased their db pool size so
that every thread of the executor could get its own connection. Clients didn't
do this, because they didn't really spawn their own thread so whatever
configuration was set was considered correct.
When we introduced Sidekiq we ended up in a slightly odd situation where only
orchestrators were considered executors and other Sidekiq workers were treated
as clients. This also meant, the clients didn't increase their db pool size and
if pressed heavily enough, they could deplete the pool. This change makes other
non-orchestrator workers increase size of their db pools.
To verify pool size is increased, have an action print …
> Make sure sidekiq workers increase their db pool size

- lib/dynflow.rb
> fix: invalid constant exception

- lib/dynflow/action.rb
- lib/dynflow/action/suspended.rb
- lib/dynflow/action/timeouts.rb
- lib/dynflow/clock.rb
- lib/dynflow/director.rb
- lib/dynflow/dispatcher.rb
- lib/dynflow/dispatcher/client_dispatcher.rb
- lib/dynflow/dispatcher/executor_dispatcher.rb
- lib/dynflow/executors/abstract/core.rb
- lib/dynflow/executors/parallel.rb
- lib/dynflow/testing/in_thread_executor.rb
- lib/dynflow/testing/in_thread_world.rb
- lib/dynflow/world.rb
- test/dispatcher_test.rb
Optional events do not raise an exception if they cannot be delivered.
> Allow marking events as optional

- examples/chunked_output_benchmark.rb
- lib/dynflow/action.rb
- lib/dynflow/execution_plan/steps/abstract_flow_step.rb
- lib/dynflow/persistence.rb
- lib/dynflow/persistence_adapters/sequel.rb
- lib/dynflow/persistence_adapters/sequel_migrations/021_create_output_chunks.rb
- web/views/flow_step.erb
The benchmark reads a list of words and then stores first `$count` words as the action's output, grouping them into groups of `$group` words.
```
bundle exec ruby examples/chunked_output_benchmark.rb                                                                                                                                                                     
World 9c3f42c8-e828-471e-8ded-a9fa9f9378e5 started...
user       system     total    real
regular    1000 by    100  0.052024   0.006064   0.058088 (  0.049565)
chunked    1000 by    100  0.041618   0.007773   0.049391 (  0.041637)
regular  10_000 by    100  1.085945   0.070478   1.156423 (  1.097117)
chunked  10_000 by    100  0.481077   0.030642   0.511719 (  0.458789)
regular  10_000 by   1000  0.117079   0.001061   0.118140 ( …
```
> Add support for chunked outputs

- lib/dynflow/delayed_executors/abstract_core.rb
- lib/dynflow/director.rb
- lib/dynflow/dispatcher.rb
- lib/dynflow/dispatcher/client_dispatcher.rb
- lib/dynflow/dispatcher/executor_dispatcher.rb
- lib/dynflow/executors/abstract/core.rb
- lib/dynflow/executors/parallel.rb
- lib/dynflow/testing.rb
- lib/dynflow/testing/dummy_coordinator.rb
- lib/dynflow/testing/dummy_world.rb
- lib/dynflow/world.rb
- test/future_execution_test.rb
Before this patch, planning of delayed plans was done by the delayed executor
actor, which runs in the orchestrator process. This had several drawbacks. The
polling interval used by the delayed executor could increase when it was
performing planning, it could have required additional ActiveRecord connection
and it required the entire application environment to be loaded.
With this change, the actual planning is dispatched through connector to the
workers. To prevent planning a plan twice, a flag is set on the delayed plan
record to indicate it is already being handled. Deletion of delayed plan record
is moved to the worker performing the actual planning.
This also allows us to "plan elsewhere", kick off a task but let another process
perform the plan phase without blocking the client with …
> Dispatch delayed plan planning through connector 

- lib/dynflow/persistence_adapters/sequel_migrations/023_sqlite_workarounds.rb
Older sqlite raise foreign key constraint errors even though the data is valid.
The same code works with newer sqlite so I guess it is a bug in sqlite which was
fixed in the meantime.
> Fix odd behavior on sqlite 3.7.17

- Gemfile
- lib/dynflow/persistence_adapters/sequel_migrations/022_store_flows_as_msgpack.rb
MultiJson provides a common interface over several JSON parsers. Sadly some of
the parsers have subtle differences.
```ruby
require 'json'
require 'oj'
example = '{"key": 1637704901.3995261}'
Oj.load(example)['key'].class # => BigDecimal
JSON.parse(example)['key'].class # => Float
```
> Use JSON directly in json to msgpack migration

- lib/dynflow/execution_plan/hooks.rb
Before
```
[2022-01-27 17:34:40.019 #854015] ERROR -- dynflow: Failed to run hook 'halt' for action 'SingletonExampleA'
```
After
```
[2022-01-27 17:34:07.272 #853880] ERROR -- dynflow: Failed to run hook 'halt' for action 'SingletonExampleA'                                                                                                                                                                          
[2022-01-27 17:34:07.272 #853880] ERROR -- dynflow: wrong number of arguments (given 1, expected 0) (ArgumentError)                                                                                                                                                                   
examples/singletons.rb:29:in `halt' …
```
> Log errors logged during hook runs with error loglevel

- lib/dynflow/rails/configuration.rb
Fixing changes introduced in https://github.com/Dynflow/dynflow/pull/410, where `::Rails.application.config.database_configuration[::Rails.env]` doesn't load data from the `DATABASE_URL` variable
> Use ::ActiveRecord::Base.configurations.configs_for

- lib/dynflow/director.rb
- lib/dynflow/executors/sidekiq/core.rb
- lib/dynflow/rails/configuration.rb
- lib/dynflow/world.rb
Dynflow has a built in subcomponent which runs inside the orchestrator and periodically dispatches delayed execution plans scheduled for the future. Once the delayed plan is properly planned, the delay record (the thing saying "an execution plan $X should be executed at time $T") is destroyed. There are some safeguards in place to ensure a single delayed plan does not get planned multiple times. 
Issue 1:
In sidekiq-based deployments, the delayed plan dispatching subcomponent is started too early, while the rest of the orchestrator is still doing world validity checks. This can lead to a situation where the subcomponent dispatches a single delayed plan multiple times.
Issue 2:
When delayed plans get dispatched multiple times, the safeguards are not handling it properly. The safeguards …
> Fix oddities in delayed planning

- examples/sub_plans_v2.rb
- lib/dynflow/action.rb
- lib/dynflow/action/v2.rb
- lib/dynflow/action/v2/with_sub_plans.rb
- test/v2_sub_plans_test.rb
The previous implementation of sub plans API comprised of several modules which could be layered on top of each other. This made the code somewhat hard to follow, not all of the modules worked in all scenarios as some relied on an executor being a single process.
The v2 flattens all the modules into a single one and drastically reduces the amount of possible combinations. Sub plans are spawned in batches and then the parent polls until the sub plans finish.
It also includes support for limitting the number of sub-plans that may be running at a given time, without relying on the throttle limitter and thus should be safe in multi-process environments. Under the hood it dynamically alters the batch size to honor the concurrency limit.
TODO:
> Introduce v2 for sub-plans

- lib/dynflow/action/v2/with_sub_plans.rb
This will only happen if there were any sub-plans which were not planned yet when the cancel event was processed.
> Call the on_planning_finished on cancel

- examples/remote_executor.rb
- lib/dynflow.rb
- lib/dynflow/executors/sidekiq/core.rb
- lib/dynflow/rails/configuration.rb
like
```
WARN: `config.options[:key] = value` is deprecated, use `config[:key] = value`
```
#431
> Access sidekiq config using a non-deprecated way

- .github/workflows/ruby.yml
- lib/dynflow/action/timeouts.rb
- lib/dynflow/coordinator.rb
- lib/dynflow/executors/parallel.rb
- lib/dynflow/executors/parallel/pool.rb
- lib/dynflow/persistence_adapters/sequel.rb
- lib/dynflow/persistence_adapters/sequel_migrations/018_add_uuid_column.rb
- lib/dynflow/telemetry.rb
- lib/dynflow/testing/factories.rb
- lib/dynflow/testing/mimic.rb
- lib/dynflow/world.rb
These were fixed
```
lib/dynflow/coordinator.rb:149: warning: method redefined; discarding old to_s
lib/dynflow/coordinator.rb:133: warning: previous definition of to_s was here
lib/dynflow/persistence_adapters/sequel.rb:102: warning: assigned but unused variable - output_chunks
lib/dynflow/action/timeouts.rb:13: warning: mismatched indentations at 'end' with 'module' at 3
lib/dynflow/executors/parallel.rb:27: warning: assigned but unused variable - error
lib/dynflow/executors/parallel/pool.rb:27: warning: method redefined; discarding old queue_size
lib/dynflow/executors/parallel/pool.rb:19: warning: previous definition of queue_size was here
lib/dynflow/world.rb:300: warning: assigned but unused variable - e
lib/dynflow/telemetry.rb:21: warning: `&' interpreted as argument prefix …
```
> Fix warnings that started popping up when running on ruby 3

- lib/dynflow/executors/sidekiq/core.rb
There are some changes coming in Sidekiq 7 that will need changes on our side and currently Sidekiq emits lots of warnings about it. We are aware of the issue, but until we resolve it properly, it doesn't make sense to spam all the users' logs with it.
> Suppress serialization warnings from Sidekiq

- lib/dynflow.rb
This fixes the following deprecation warning:
WARN: `config.options[:key] = value` is deprecated, use `config[:key] = value`: ["/usr/share/gems/gems/dynflow-1.8.2/lib/dynflow.rb:28:in `block in process_world'", "/usr/share/gems/gems/sidekiq-6.5.12/lib/sidekiq.rb:142:in `configure_server'"]
> Fix deprecation warning

- lib/dynflow/coordinator.rb
- lib/dynflow/world.rb
- lib/dynflow/world/invalidation.rb
> Sidekiq, locks and invalidation

- examples/halt.rb
- lib/dynflow/coordinator.rb
- lib/dynflow/director.rb
- lib/dynflow/director/execution_plan_manager.rb
- lib/dynflow/director/running_steps_manager.rb
- lib/dynflow/dispatcher.rb
- lib/dynflow/dispatcher/client_dispatcher.rb
- lib/dynflow/dispatcher/executor_dispatcher.rb
- lib/dynflow/execution_plan.rb
- lib/dynflow/executors/abstract/core.rb
- lib/dynflow/executors/parallel.rb
- lib/dynflow/world.rb
- lib/dynflow/world/invalidation.rb
- test/executor_test.rb
Up until now, Dynflow only had support for clean cancellation. Upon cancellation
a cancel event was sent to all cancellable suspended and running steps and it
was the action's responsibility to cancel itself. However, there were actions
which just weren't cancellable at all.
This commit adds support for halting execution plans. The actions are completely
unaware of this, on halt dynflow just destroys its internal state about a given
execution plan and turns it to stopped state. It does not remove running steps
from workers as we currently don't have any real means of doing so. Any pending
events will be rejected. In other words, halting an execution plan ensure it
will not run any further.
> Add support for halting execution plans

- lib/dynflow/action/v2/with_sub_plans.rb
- lib/dynflow/persistence.rb
- lib/dynflow/persistence_adapters/abstract.rb
- lib/dynflow/persistence_adapters/sequel.rb
This PR proposes to mark every sub plan which finishes as not successful
after the parent execution plan receives the cancel directive as
cancelled. This is to be consistent with how a task is evaluated as
cancelled in the foreman project.
This PR has an additional effect which makes the parent execution plan
always finish with warning if at least one sub plan is cancelled as a
response to the `cancel` event. Until now, it could either finish with
success if all subplans either finished with success or were not yet
queued for execution or it could finish with warning if already pending
sub plan was cancelled and finished with the `error` result.  In
summary, this additional change unifies the behavior of a cancelled
execution plan if there is anything left to cancel.
> Edit how failed_count and cancelled_count is calculated

- lib/dynflow/dispatcher.rb
It is not used anywhere. Previously we were leaving it unset, which was fine in single-process scenarios (such as tests and development environments), but failed in cases where the request took a round trip through the database.
> Drop optional field from Halt request variant
