lib/dynflow/action/polling.rb
Polling action:
- made ```done?``` method able to raise an exception and stop the action
- added ```on_finish``` method
=> Polling action tweaks

doc/pages/source/documentation/index.md
Suggestions as a PR.
Also, we should unify the `running phase` vs. `run phase`
=> Some updates for the documentation

doc/pages/source/documentation/index.md
Meanwhile you covered what I wanted to push :-) So at least one sentence I had in my version that might or might not be useful.
=> More info about World

examples/example_helper.rb, examples/orchestrate.rb, examples/sub_plan_concurrency_control.rb, lib/dynflow.rb, lib/dynflow/action/with_sub_plans.rb, lib/dynflow/config.rb, lib/dynflow/delayed_plan.rb, lib/dynflow/dispatcher/executor_dispatcher.rb, lib/dynflow/execution_plan.rb, lib/dynflow/execution_plan/steps/run_step.rb, lib/dynflow/semaphores.rb, lib/dynflow/semaphores/abstract.rb, lib/dynflow/semaphores/aggregating.rb, lib/dynflow/semaphores/dummy.rb, lib/dynflow/semaphores/stateful.rb, lib/dynflow/throttle_limiter.rb, lib/dynflow/world.rb, test/action_test.rb, test/concurrency_control_test.rb, test/future_execution_test.rb, test/middleware_test.rb, test/prepare_travis_env.sh, test/semaphores_test.rb, test/test_helper.rb
~~Global level is per-executor.~~
=> Fixes #10751 - Concurrency level control

lib/dynflow/world.rb
Due to too general rescue in concurrent ruby, we need to call the exit
in separate thread, otherwise the SystemExit error gets caught and
nothing happens.
Also, I've made the work with `@exit_on_terminate` thread-safe,
which should not be a case in MRI, but it's potentially unsynchronized
in future Ruby implementations.
=> Fix world auto-termination

Rakefile
And also made travis to fail on output size limit
=> The warnings in tests just made a mess form the the test output

lib/dynflow/coordinator.rb, lib/dynflow/world.rb, test/coordinator_test.rb
There is a potential race condition, where a plan is still in planned state,
but some executor has already locked it.
=> Check plan is not lock before auto_execution

lib/dynflow/action.rb, lib/dynflow/middleware.rb, lib/dynflow/middleware/stack.rb, lib/dynflow/middleware/world.rb, lib/dynflow/persistence.rb, lib/dynflow/web/console_helpers.rb, test/middleware_test.rb, test/support/middleware_example.rb
This commit allows to hook in the action when the data are presented
to the user, for example to filter some sensitive information.
=> Middleware support for present phase

dynflow.gemspec, lib/dynflow/action/rescue.rb, lib/dynflow/execution_plan.rb, test/rescue_test.rb, test/support/rescue_example.rb
=> Adds Fail rescue strategy

doc/pages/source/documentation/index.md
Please double check that I don't make up something :-)
=> Improve finalize documentation

web/views/layout.erb
Solves the same thing as https://github.com/Dynflow/dynflow/pull/178 differently
=> Fixes #12729 - Allow adding navbar links

lib/dynflow/director/running_steps_manager.rb, lib/dynflow/executors/abstract.rb, lib/dynflow/testing/in_thread_executor.rb, lib/dynflow/testing/in_thread_world.rb, test/test_helper.rb, test/testing_test.rb
+ improvements in terminate interface of in thread world
=> Refs #17283 - fix rescuing from InThreadExecutor

lib/dynflow.rb, lib/dynflow/active_job/queue_adapter.rb, lib/dynflow/rails.rb, lib/dynflow/rails/configuration.rb, lib/dynflow/rails/daemon.rb
I made this PR depend on https://github.com/Dynflow/dynflow/pull/216 - so let's try to get them in order to reduce the diff a little. You should be familiar with most of this code. Check out its usage on https://github.com/theforeman/foreman/pull/4316#discussion_r102676503
=> Rails initialization

lib/dynflow/executors/parallel/core.rb
Added some more text to make it look less like an error.
=> Core dump tools look for core terminated.

doc/pages/source/documentation/index.md
I'm very open to any feedback on this one.
=> Add docs for how to use subplans

lib/dynflow/action.rb, test/support/code_workflow_example.rb
The trigger method conflicts with that of WithSubTasks
=> Rename trigger to triggering_action

lib/dynflow/action.rb, lib/dynflow/config.rb, lib/dynflow/director.rb, lib/dynflow/dispatcher.rb, lib/dynflow/persistence_adapters/sequel_migrations/001_initial.rb, lib/dynflow/persistence_adapters/sequel_migrations/003_parent_action.rb
Fixnum was deprecated in ruby 2.4.0.
=> Use Integer instead of Fixnum

lib/dynflow/serializable.rb
According to my measurements, this method is called about 20k times per sync,
it is worth optimizing. Looks like we have most strings and hashes than
everything else, this makes it faster.
```
eforeman/tfm/root/usr/share/gems/gems/dynflow-0.8.24/lib/dynflow/serializable.rb     43                            ===  10895
eforeman/tfm/root/usr/share/gems/gems/dynflow-0.8.24/lib/dynflow/serializable.rb     39              recursive_to_hash   5175
eforeman/tfm/root/usr/share/gems/gems/dynflow-0.8.24/lib/dynflow/serializable.rb     41                          first   5134
eforeman/tfm/root/usr/share/gems/gems/dynflow-0.8.24/lib/dynflow/serializable.rb     48                         update   4619
sr/share/gems/gems/dynflow-0.8.24/lib/dynflow/execution_plan/output_reference.rb     24 …
```
=> Optimized ordering during serialization

Gemfile, dynflow.gemspec, lib/dynflow/config.rb, lib/dynflow/rails.rb, lib/dynflow/rails/configuration.rb, lib/dynflow/rails/daemon.rb, lib/dynflow/testing/dummy_world.rb, test/daemon_test.rb, test/future_execution_test.rb, test/support/rails/config/environment.rb
Needs to be manual tested and tests from https://github.com/theforeman/foreman-tasks/commit/d3051b91d63a1c809b78fbd48187ba364c391a89 have to be ported, this is preliminary
=> Port memory profiling from foreman-tasks

lib/dynflow/action/with_bulk_sub_plans.rb, lib/dynflow/action/with_polling_sub_plans.rb, lib/dynflow/action/with_sub_plans.rb, lib/dynflow/execution_plan.rb, lib/dynflow/persistence.rb, lib/dynflow/persistence_adapters/abstract.rb, lib/dynflow/persistence_adapters/sequel.rb, test/action_test.rb, test/batch_sub_tasks_test.rb, test/concurrency_control_test.rb, test/persistence_test.rb
=> [WIP] Performance fixes

doc/pages/source/documentation/index.md
Docs for https://github.com/Dynflow/dynflow/pull/270
=> [WIP] Add docs for execution plan hooks

lib/dynflow/executors.rb
Always clearing the connections broke tests in REX
=> Clear AR connections only if there are no open transactions

lib/dynflow/world.rb, lib/dynflow/world/invalidation.rb, test/abnormal_states_recovery_test.rb, test/support/dummy_example.rb
=> Honor rescue strategy on abnormal termination

lib/dynflow/testing/assertions.rb
even if we have aliases, no need to use them ourself :)
=> fix assert_action_planned typo

lib/dynflow/persistence_adapters/sequel_migrations/011_placeholder.rb, lib/dynflow/persistence_adapters/sequel_migrations/018_add_uuid_column.rb, test/abnormal_states_recovery_test.rb
We were checking on `database_type == :postgresql`, while the
database_type I see with psql is `:postgres`.
=> Fix setting uuid type in postgres

.travis.yml
https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment
=> Fix tests on travis

lib/dynflow/clock.rb
Based on https://github.com/Dynflow/dynflow/pull/310
=> Implement Clock using concurrent-ruby primitives

.travis.yml
Also removed the deprecated `sudo:` key and fixed `language:`
=> Start MySQL service only in specific job

Gemfile, examples/remote_executor.rb, lib/dynflow/action.rb, lib/dynflow/execution_plan/steps/abstract.rb, lib/dynflow/executors/sidekiq/worker_jobs.rb, lib/dynflow/persistence.rb, lib/dynflow/persistence_adapters/sequel.rb, lib/dynflow/testing/dummy_step.rb
~~Based on https://github.com/Dynflow/dynflow/pull/329~~
Redmine: https://projects.theforeman.org/issues/27411
=> Worker crash recovery

lib/dynflow/action.rb, lib/dynflow/action/suspended.rb, lib/dynflow/clock.rb, lib/dynflow/dispatcher.rb, lib/dynflow/dispatcher/executor_dispatcher.rb, lib/dynflow/execution_plan/steps/abstract.rb, lib/dynflow/execution_plan/steps/abstract_flow_step.rb, lib/dynflow/executors/abstract/core.rb, lib/dynflow/executors/parallel.rb, lib/dynflow/executors/parallel/core.rb, lib/dynflow/executors/parallel/pool.rb, lib/dynflow/executors/sidekiq/orchestrator_jobs.rb, lib/dynflow/executors/sidekiq/worker_jobs.rb, lib/dynflow/serializer.rb, lib/dynflow/testing/dummy_executor.rb, lib/dynflow/testing/dummy_world.rb, lib/dynflow/testing/factories.rb, lib/dynflow/testing/in_thread_executor.rb, lib/dynflow/testing/in_thread_world.rb, lib/dynflow/world.rb, test/action_test.rb, test/dispatcher_test.rb, test/executor_test.rb, test/support/dummy_example.rb, test/test_helper.rb
Redmine: https://projects.theforeman.org/issues/27410
=> Fixes #27410 - use orchestrator clock for suspending

docker-compose.yml, examples/remote_executor.rb, lib/dynflow/director.rb, lib/dynflow/director/execution_plan_manager.rb, lib/dynflow/director/running_steps_manager.rb, lib/dynflow/executors/sidekiq/core.rb, lib/dynflow/executors/sidekiq/orchestrator_jobs.rb, lib/dynflow/executors/sidekiq/worker_jobs.rb, test/executor_test.rb
=> Orchestrator crash recovery

lib/dynflow/executors/sidekiq/core.rb
follows https://github.com/Dynflow/dynflow/pull/340
=> Fix sidekiq core api

lib/dynflow/action.rb, lib/dynflow/action/polling.rb, lib/dynflow/action/timeouts.rb, lib/dynflow/action/with_bulk_sub_plans.rb, lib/dynflow/action/with_polling_sub_plans.rb, lib/dynflow/clock.rb, lib/dynflow/executors/abstract/core.rb, lib/dynflow/testing/dummy_executor.rb, lib/dynflow/testing/factories.rb, lib/dynflow/testing/in_thread_executor.rb, lib/dynflow/testing/in_thread_world.rb, test/action_test.rb, test/test_helper.rb
Use the `plan_event` API for sending events to the action.
=> Refs #27410 - use new API within action

lib/dynflow/director/running_steps_manager.rb
=> Fix undefined method 'result' error on termination

lib/dynflow/actor.rb
If desired, their collection can be enabled by setting `DYNFLOW_FULL_BACKTRACE` environment variable. Additionally, the length of the output can be limited by setting `DYNFLOW_BACKTRACE_LIMIT`.
Fixes #388
=> Do not collect full stacktraces by default

lib/dynflow/execution_plan.rb, lib/dynflow/execution_plan/hooks.rb, test/execution_plan_hooks_test.rb
=> Run hooks when execution plan is first created

lib/dynflow/rails/configuration.rb
this makes the change from bd0b3d71c9403da553e98ed2c75bf1c568315cf9 backwards compatible
=> load config in a way that's compatible with ActiveRecord 6.0 and 6.1

lib/dynflow/persistence_adapters/sequel.rb
For testing run dynflow with `DYNFLOW_SQL_LOG=1`
=> Limit update SQL queries to only columns that changed
